-- شغّل هذا الملف داخل Supabase Studio > SQL Editor
-- ملاحظة: في الإنتاج الحالي tasks.id من نوع uuid
-- هذا الملف مرجع حقيقي لما يستخدمه التطبيق فعلياً (مزامنة أغسطس 2026)

-- ============================================================
-- tasks
-- ============================================================

create table if not exists public.tasks (
  id           uuid primary key default gen_random_uuid(),
  title        text not null,
  quadrant     text not null default 'important-urgent'
               check (quadrant in (
                 'important-urgent',
                 'important-not-urgent',
                 'not-important-urgent',
                 'not-important-not-urgent'
               )),
  context      text not null default 'work',
  subtasks     jsonb not null default '[]'::jsonb,
  completed    boolean not null default false,
  status       text not null default 'not_started'
               check (status in (
                 'not_started',
                 'in_progress',
                 'completed',
                 'deferred',
                 'cancelled'
               )),
  archived     boolean not null default false,
  archived_at  timestamptz,
  notes        text default '',
  due_date     date,
  duration     integer not null default 1,
  sort_order   integer not null default 0,
  recurrence   text default null,
  recurrence_days integer[] default null,
  external_source text default null,
  external_id     text default null,
  external_url    text default null,
  external_meta   jsonb default null,
  last_synced_at  timestamptz,
  time_spent_seconds integer not null default 0,
  created_at   timestamptz not null default now(),
  completed_at timestamptz
);

-- ترحيل tasks (بيئات قديمة)
alter table public.tasks add column if not exists context text not null default 'work';
alter table public.tasks add column if not exists subtasks jsonb not null default '[]'::jsonb;
alter table public.tasks drop constraint if exists tasks_context_check;
alter table public.tasks add column if not exists sort_order integer not null default 0;
alter table public.tasks add column if not exists recurrence text default null;
alter table public.tasks add column if not exists recurrence_days integer[] default null;
alter table public.tasks add column if not exists external_source text default null;
alter table public.tasks add column if not exists external_id text default null;
alter table public.tasks add column if not exists external_url text default null;
alter table public.tasks add column if not exists external_meta jsonb default null;
alter table public.tasks add column if not exists last_synced_at timestamptz;
alter table public.tasks add column if not exists archived boolean not null default false;
alter table public.tasks add column if not exists archived_at timestamptz;
alter table public.tasks add column if not exists time_spent_seconds integer not null default 0;

-- عمود status (مطلوب من useTrello / taskStatus / TaskModal)
alter table public.tasks add column if not exists status text;
update public.tasks
  set status = case
    when completed = true then 'completed'
    else coalesce(nullif(btrim(status), ''), 'not_started')
  end
  where status is null or btrim(status) = '';
alter table public.tasks alter column status set default 'not_started';
alter table public.tasks alter column status set not null;
do $$
begin
  alter table public.tasks drop constraint if exists tasks_status_check;
  alter table public.tasks
    add constraint tasks_status_check
    check (status in (
      'not_started',
      'in_progress',
      'completed',
      'deferred',
      'cancelled'
    ));
exception when others then null;
end $$;

update public.tasks set context = 'work' where context is null or btrim(context) = '';
update public.tasks set archived = false where archived is null;

create unique index if not exists tasks_external_unique
  on public.tasks (external_source, external_id)
  where external_source is not null and external_id is not null;

create index if not exists tasks_created_at_idx on public.tasks (created_at desc);
create index if not exists tasks_quadrant_sort_idx on public.tasks (quadrant, sort_order);
create index if not exists tasks_context_idx on public.tasks (context);
create index if not exists tasks_archived_idx on public.tasks (archived);
create index if not exists tasks_status_idx on public.tasks (status);

-- ============================================================
-- pomodoro_sessions
-- ============================================================

create table if not exists public.pomodoro_sessions (
  id                 bigint generated by default as identity primary key,
  task_id            uuid references public.tasks(id) on delete set null,
  task_title         text,
  context            text not null default 'work',
  mode               text not null check (mode in ('work', 'break')),
  planned_seconds    integer not null default 1500,
  elapsed_seconds    integer not null default 0,
  completed          boolean not null default true,
  started_at         timestamptz not null,
  ended_at           timestamptz not null default now(),
  created_at         timestamptz not null default now()
);

create index if not exists pomodoro_sessions_started_at_idx
  on public.pomodoro_sessions (started_at desc);
create index if not exists pomodoro_sessions_context_idx
  on public.pomodoro_sessions (context);
create index if not exists pomodoro_sessions_task_id_idx
  on public.pomodoro_sessions (task_id);

-- ============================================================
-- integrations (Trello وغيرها)
-- تحذير أمني: api_key / access_token حالياً قابلة للقراءة عبر anon
-- إلى أن يُنقل الاعتماد إلى app_secrets أو يُقيَّد بـ Auth
-- ============================================================

create table if not exists public.integrations (
  id            bigint generated by default as identity primary key,
  provider      text not null unique,
  api_key       text,
  access_token  text,
  settings      jsonb default '{}'::jsonb,
  last_sync_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ============================================================
-- task_notes — مسودات مرتبطة بمهمة + مفكرة مستقلة (task_id null)
-- يستخدمها: useTaskNotes.js ، useStandaloneNotes.js
-- ============================================================

create table if not exists public.task_notes (
  id          uuid primary key default gen_random_uuid(),
  task_id     uuid references public.tasks(id) on delete cascade,
  title       text not null default 'مسودة بدون عنوان',
  content_md  text not null default '',
  note_type   text not null default 'note' check (note_type in ('note', 'checklist', 'decision', 'reference')),
  labels      text[] not null default '{}'::text[],
  is_pinned   boolean not null default false,
  checklist   jsonb not null default '[]'::jsonb,
  context     text,
  project_id  uuid references public.projects(id) on delete set null,
  board_stage text not null default 'capture' check (board_stage in ('capture', 'shape', 'next')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists task_notes_task_id_idx on public.task_notes (task_id);
create index if not exists task_notes_updated_at_idx on public.task_notes (updated_at desc);
create index if not exists task_notes_standalone_idx
  on public.task_notes (updated_at desc)
  where task_id is null;
create index if not exists task_notes_standalone_pinned_idx
  on public.task_notes (is_pinned desc, updated_at desc)
  where task_id is null;
create index if not exists task_notes_standalone_context_idx
  on public.task_notes (context)
  where task_id is null and context is not null;
create index if not exists task_notes_standalone_project_idx
  on public.task_notes (project_id)
  where task_id is null and project_id is not null;
create index if not exists task_notes_standalone_board_stage_idx
  on public.task_notes (board_stage, updated_at desc)
  where task_id is null;

alter table public.task_notes add column if not exists note_type text not null default 'note';
alter table public.task_notes add column if not exists labels text[] not null default '{}'::text[];
alter table public.task_notes add column if not exists is_pinned boolean not null default false;
alter table public.task_notes add column if not exists checklist jsonb not null default '[]'::jsonb;
alter table public.task_notes add column if not exists context text;
alter table public.task_notes add column if not exists project_id uuid references public.projects(id) on delete set null;
alter table public.task_notes add column if not exists board_stage text not null default 'capture';
alter table public.task_notes drop constraint if exists task_notes_board_stage_check;
alter table public.task_notes add constraint task_notes_board_stage_check check (board_stage in ('capture', 'shape', 'next'));
alter table public.task_notes drop constraint if exists task_notes_note_type_check;
alter table public.task_notes add constraint task_notes_note_type_check check (note_type in ('note', 'checklist', 'decision', 'reference'));

-- ============================================================
-- library_items — مكتبة المصادر (مساحة الاستراحة)
-- يستخدمها: useLibrary.js
-- ============================================================

create table if not exists public.library_items (
  id           uuid primary key default gen_random_uuid(),
  category     text not null default 'general',
  title        text not null,
  description  text not null default '',
  source_name  text not null default 'مصدرك الخاص',
  url          text default null,
  is_curated   boolean not null default false,
  created_at   timestamptz not null default now()
);

create index if not exists library_items_created_at_idx
  on public.library_items (created_at);
create index if not exists library_items_category_idx
  on public.library_items (category);

-- ============================================================
-- app_settings — صف واحد ثابت id = 1
-- يستخدمها: useWorkDaysSetting.js + إعدادات الدفع
-- ============================================================

create table if not exists public.app_settings (
  id            integer primary key default 1 check (id = 1),
  work_days     integer[] not null default '{0,1,2,3,4}'::integer[],
  push_enabled  boolean not null default false,
  updated_at    timestamptz not null default now()
);

insert into public.app_settings (id, work_days, push_enabled)
values (1, '{0,1,2,3,4}'::integer[], false)
on conflict (id) do nothing;

alter table public.app_settings add column if not exists work_days integer[] not null default '{0,1,2,3,4}'::integer[];
alter table public.app_settings add column if not exists push_enabled boolean not null default false;
alter table public.app_settings add column if not exists updated_at timestamptz not null default now();

-- ============================================================
-- push_subscriptions + app_secrets + time_sessions
-- ============================================================

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  device_label text default null,
  created_at timestamptz not null default now()
);

-- مفاتيح VAPID + أي أسرار. RLS مفعّل بدون أي سياسة =
-- وصول حصري لـ service_role (داخل Edge Functions فقط).
create table if not exists public.app_secrets (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.time_sessions (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer
);
create index if not exists time_sessions_task_idx on public.time_sessions (task_id);
create index if not exists time_sessions_started_idx on public.time_sessions (started_at);

-- ============================================================
-- RLS — الوضع الحالي (تطوير / مستخدم واحد)
-- ملاحظة: allow-all مؤقت حتى يصل Auth (المجموعة الثالثة)
-- app_secrets عمداً بلا policy = محمي من anon
-- ============================================================

alter table public.tasks enable row level security;
alter table public.integrations enable row level security;
alter table public.pomodoro_sessions enable row level security;
alter table public.task_notes enable row level security;
alter table public.library_items enable row level security;
alter table public.app_settings enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.time_sessions enable row level security;
alter table public.app_secrets enable row level security;
-- لا تُضف أي policy على app_secrets

drop policy if exists "Allow all access to tasks" on public.tasks;
create policy "Allow all access to tasks"
  on public.tasks for all using (true) with check (true);

drop policy if exists "Allow all access to integrations" on public.integrations;
create policy "Allow all access to integrations"
  on public.integrations for all using (true) with check (true);

drop policy if exists "Allow all access to pomodoro_sessions" on public.pomodoro_sessions;
create policy "Allow all access to pomodoro_sessions"
  on public.pomodoro_sessions for all using (true) with check (true);

drop policy if exists "Allow all access to task_notes" on public.task_notes;
create policy "Allow all access to task_notes"
  on public.task_notes for all using (true) with check (true);

drop policy if exists "Allow all access to library_items" on public.library_items;
create policy "Allow all access to library_items"
  on public.library_items for all using (true) with check (true);

drop policy if exists "Allow all access to app_settings" on public.app_settings;
create policy "Allow all access to app_settings"
  on public.app_settings for all using (true) with check (true);

drop policy if exists "Allow all for development" on public.push_subscriptions;
create policy "Allow all for development"
  on public.push_subscriptions for all using (true) with check (true);

drop policy if exists "Allow all for development" on public.time_sessions;
create policy "Allow all for development"
  on public.time_sessions for all using (true) with check (true);

-- Realtime
do $$
begin
  alter publication supabase_realtime add table public.tasks;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.task_notes;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.library_items;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.app_settings;
exception when duplicate_object then null;
end $$;

-- ============================================================
-- ملاحظات تشغيل
-- ============================================================
-- 1) Edge Function "send-push" تستخدم service_role + app_secrets (VAPID).
-- 2) pg_cron: mahd-morning-push / mahd-evening-push إن وُجدت.
-- 3) قبل Auth: لا تعتمد على RLS للعزل — التطبيق شخصي/فريق صغير فقط.
-- 4) الخطوة التالية المخططة: تأمين send-push (JWT) ثم credentials تريلو.

-- ============================================================
-- projects + task deliverables / recurrence history
-- ============================================================
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  context text not null default 'work',
  name text not null,
  description text not null default '',
  status text not null default 'active' check (status in ('active','completed','archived')),
  due_date date,
  color text not null default '#159a76',
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks add column if not exists project_id uuid references public.projects(id) on delete set null;
alter table public.tasks add column if not exists deliverable text not null default '';
alter table public.tasks add column if not exists deliverable_url text default null;
alter table public.tasks add column if not exists occurrence_log jsonb not null default '{}'::jsonb;

create index if not exists projects_context_idx on public.projects(context);
create index if not exists projects_status_idx on public.projects(status);
create index if not exists tasks_project_id_idx on public.tasks(project_id);

alter table public.projects enable row level security;
drop policy if exists "Allow all access to projects" on public.projects;
create policy "Allow all access to projects"
  on public.projects for all using (true) with check (true);
